---
title: "Problem Set Sandbox"
author: "Matthew Aiello-Lammens"
date: "1/31/2018"
output: html_document
---

***

# 2016 PS 2

# DUE Monday February 22

# Part 1

Use the `iris` dataset that comes with R to answer the following questions.
We worked with this dataset in class during **Week 2**.
As a reminder, you can 'load' the `iris` dataset using the following command:

```
data(iris)
```

1. Calculate the **mean**, **standard deviation**, and an additional **measure of location** and **measuer of dispersion and variability** of your choosing for **Petal Length** for the full `iris` dataset **AND** for each species separately. 
In words, describe the differences you observe between species, and between individual species and the full dataset. 
Be sure to identify which measures of your choosing you are calculating. 
You may want to consult *Logan; Table 3.3* when deciding on additional measures.
**(5 pnts)**

2. Construct a **boxplot** for **Petal Length** using the `iris` dataset. 
Both the *Logan* and *Quinn & Keough* texts provide extensive information on boxplots.
You can use `base` R or `ggplot2`. 
See [this site](http://www.cookbook-r.com/Graphs/Plotting_distributions_(ggplot2)/) for a good outline of constructing a boxplot with `ggplot2`.
In your plot, each box should represent a different species.
Describe each component of a generic boxplot, and describe why we might be interested in each value that is represented.
**(10 pnts)**

* **BONUS** Construct separate **density histograms** for **Petal Length** for each species. 
Overlay on top of the histograms curves for the **normal distributions** with the means and standard deviations calculated in (1) above. 
Hint 1: check out [this site](http://www.statmethods.net/advgraphs/probability.html) for information on plotting a normal distribution.
Hint 2: You can use `ggplot2` to overlay the normal onto your histogram, or in `base` R you can try adding `add = TRUE` to the `plot` function.
**(5 bonus pnts)**

# Part 2

* Recall the M&Ms we worked with in Week 1. 
Using the same logic we used to derive the **binomial distribution**, derive the probability of obtaining a given combination of colors in our bag.
([Hint](https://en.wikipedia.org/wiki/Multinomial_distribution)). 
Calculate the probability of getting your specific bag (our data are [here](http://mlammens.github.io/Biostats/data/class_mm_data.csv))
**(5 pnts)**

***

Problem Set xxx: Probability Distributions
========================================================


## Part 1 (10 pnts for function; 5 pnts for figures)

Write a function in R that:

1. draws a sample ${X_1,X_2,…,X_{n}}$ of size $n$ from the normal distribution $N(\mu, \sigma^2 )$ (you are free to choose $\mu$ and $\sigma^2 \gt 0$), 
2. calculates the standard error of the mean, and 
3. calculates 

$$
\frac{ \bar{X} - \mu }{ s.e.mean }
$$

This function should have three inputs $(\mu,\sigma^2,n)$ and 
one output, the value of $\frac{ \bar{X} - \mu }{ s.e.mean }$

**NB:** See Logan pp. 34-35 for an explination of how to write your own function.

Your function takes samples from the t-distribution. 
Draw a large number (10,000 is probably fine, but you can play around with it) of samples from this distribution for $n = 5$, $n =50$, and $n =500$. 
(Remember, $n$ is the number of draws from the normal distribution used to draw one sample from the t-distribution.) 
Plot these three histograms, preferably using `ggplot2` so that each histogram is on the same plot.
(You could also use the `hist` function with the option `add = T`, which will allow you to plot them all on the same plot).

## Part 2 (5 pnts)

Using 1000 random draws from the t-distribution (you can use your function or R’s built-in function here) and the Normal distribution, plot the QQ plot comparing them for $n = 5$, $n =50$, and $n =500$ (NOTE: if you are using the built-in function, you will want to set `df` to $5$, $50$, and $500$, not `n`). 
(Hint: Use the function `qqplot` and see Logan p. 118.) 
For easy comparison, put all three scatterplots on the same plot, using different colors to distinguish the three cases.