---
title: "Problem Set 3"
author: "Matthew E. Aiello-Lammens"
date: "2018-02-07"
output: html_document
---
**Please submit this homework as an R Markdown (Rmd) file.**
See the introduction to [Problem Set 1](http://mlammens.github.io/ENS-623-Research-Stats/problem_sets/Problem-set-1.html) if you need more information about the Rmd format.

#### File name

Your file should use the following naming scheme

**`[last name]_ENS623_SP18_PS2.Rmd`**

For example, 

`Lammens_ENS623_SP18_PS2.Rmd`

#### Grading note

This is a single problem worth 25 points, but partial credit will be given.

*Caveat - this example is based on a real competative relationship, but all numbers are completely fictional.*

Red fox and arctic fox compete both directly and indirectly where their species ranges meet. 
Direct competition usually involves fighting between individuals, while indirect competition usually involves competition for denning locations.
Generally, red fox can out compete arctic fox in both direct and indirect competition, but cannot physically tolerate the colder temperatures that arctic fox can.
Therefore, the red fox is primarily responsible for the southern range edge of the arctic fox.

During direct competition, an individual will "attack" as long as it has the "advantage" in the fight.
The individual maintains the "advantage" as long as it is "wins" a bout. 
If on the other hand, an individual is attacked, it will "defend".
An individual "wins-overall" when it scores 21 "wins" on its opponent. 
(This setup is similar to how raquetball is scored.)
If a red fox attacks first, it will "win" a "bout" with a probability of 0.6. 
If a red fox is attacked by an arctic fox, it will "win" the "bout" with a probability of of 0.5. 

Estimate, by simulation, the probability that during a red fox-arctic fox interaction, **a red fox will "win-overall"**. 

*Acknowledgements: This problem is a variation of one developed by Dr. Heather Lynch at Stony Brook University for her biostats class.*
